### ISSUE TITLE
EpubJS Version

### ISSUE THREAD

**Issue by paulocoutinhox** [androidovshchik/AngularEpubViewer#1]
Hi,

What epubjs you are using?

Version: 2, 3 or 4?

Thanks.

**Comment by vladkalyuzhny** [comment]
Hi
I used the **latest** in npm repo which is `0.2.21` https://www.npmjs.com/package/epubjs

**Comment by vladkalyuzhny** [comment]
i wrote it in a hurry a little
so i will be glad to get feedback
